---
title: Chainport Insights
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    image: 
    description: 
    button:
      title: 
      url: 
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
- scope:
    path: ''
    type: gallery
  values:
    image: 
    link: 
url: insights.chainport.nz
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: "\n\n"
sass:
  sass_dir: styles/
  style: compressed
per_page: 12
date_format: "%b %d, %Y"
google_analytics: UA-1666437-33
twitter:
  username: siteleaf
logo: "/assets/logo.png"
future: true
header_nav:
  Blog: "/"
  Gallery: "/gallery/"
footer_nav:
  Features: "/features/"
  Privacy: "/privacy/"
  Terms: "/terms/"
  GDPR: "/gdpr/"
scripts: '<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return
  a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script><script>window.Beacon(''init'',
  ''13d71c30-bf3c-49d8-a515-60646ded4459'')</script>

'
