---
title: Chainport Insights
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
plugins:
- jekyll-remote-theme
sass:
  sass_dir: styles/
  style: compressed
permalink: pretty
remote_theme: siteleaf/siteleaf.com
per_page: 12
date_format: "%b %d, %Y"
google_analytics: UA-1666437-33
twitter:
  username: siteleaf
logo: "/assets/logo.png"
future: true
header_nav:
  Blog: "/posts/"
footer_nav:
  Features: "/features/"
  Press: http://siteleaf.dropmark.com/326718
  Privacy: "/privacy/"
  Terms: "/terms/"
  GDPR: "/gdpr/"
  Status: http://status.siteleaf.com
  Chat: http://chat.siteleaf.com
  Twitter: https://twitter.com/siteleaf
scripts: '<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return
  a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script><script>window.Beacon(''init'',
  ''13d71c30-bf3c-49d8-a515-60646ded4459'')</script>

'
